import { jsPDF } from "jspdf";

export type PageSize = "a4" | "a3";

export async function generatePDF(imageUrl: string, title: string, size: PageSize = "a4", isPremium: boolean = false) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: size,
    compress: isPremium, // Better compression/quality for premium
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Add Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(isPremium ? 28 : 24);
  doc.text(title.toUpperCase(), pageWidth / 2, 20, { align: "center" });

  // Load Image
  return new Promise<void>((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      // Calculate dimensions to fit page while maintaining aspect ratio
      const margin = 20;
      const maxWidth = pageWidth - (margin * 2);
      const maxHeight = pageHeight - 60; 

      let imgWidth = img.width;
      let imgHeight = img.height;
      const ratio = imgWidth / imgHeight;

      if (imgWidth > maxWidth) {
        imgWidth = maxWidth;
        imgHeight = imgWidth / ratio;
      }
      if (imgHeight > maxHeight) {
        imgHeight = maxHeight;
        imgWidth = imgHeight * ratio;
      }

      const xShift = (pageWidth - imgWidth) / 2;
      const yShift = 30; 

      doc.addImage(img, "PNG", xShift, yShift, imgWidth, imgHeight, undefined, isPremium ? 'FAST' : 'SLOW');

      // Add Footer
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by DoodlePDF", pageWidth / 2, pageHeight - 10, { align: "center" });

      // Watermark for FREE users
      if (!isPremium) {
        doc.setTextColor(200, 200, 200);
        doc.setFontSize(40);
        doc.saveGraphicsState();
        doc.setGState(new (doc as any).GState({ opacity: 0.1 }));
        doc.text("DOODLE PDF FREE", pageWidth / 2, pageHeight / 2, { align: 'center', angle: 45 });
        doc.restoreGraphicsState();
      }

      doc.save(`${title.replace(/\s+/g, "_")}_coloring_page.pdf`);
      resolve();
    };
    img.onerror = () => {
      reject(new Error("Failed to load image for PDF"));
    };
    img.src = imageUrl;
  });
}
